<Project>
  <PropertyGroup>
    <OutputType>Bundle</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ImeSense.WixToolset.BootstrapperApplications.wixext" />
    <PackageReference Include="ImeSense.WixToolset.NetFx.wixext" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\TestBA\TestBAWixlib\testbawixlib.wixproj" />
    <ProjectReference Include="..\AllPuomBundle\AllPuomBundleTestBA.wixproj" />
  </ItemGroup>
</Project>