<Project>
  <PropertyGroup>
    <OutputType>Bundle</OutputType>
    <SuppressSpecificWarnings>1140</SuppressSpecificWarnings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ImeSense.WixToolset.BootstrapperApplications.wixext" />
    <PackageReference Include="ImeSense.WixToolset.NetFx.wixext" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\TestBA\TestBAWixlib\testbawixlib.wixproj" />
    <ProjectReference Include="..\PerMachinePkg\PerMachinePkg.wixproj" />
    <ProjectReference Include="..\PuomPkg1\PuomPkg1.wixproj" />
    <ProjectReference Include="..\PuomPkg2\PuomPkg2.wixproj" />
    <ProjectReference Include="..\PerUserPkg\PerUserPkg.wixproj" />
  </ItemGroup>
</Project>